output_dir: 'output/meta_2023-06-10-10-35-17161_uie-base-en_spotasoc_absa_14lap_e30_linear_lr1e-4_ls0_b16_wu0_n-1_run1'
overwrite_output_dir: False
do_train: True
do_eval: True
do_predict: True
evaluation_strategy: epoch
prediction_loss_only: False
per_device_train_batch_size: 16
per_device_eval_batch_size: 64
gradient_accumulation_steps: 1
eval_accumulation_steps: None
learning_rate: 0.0001
weight_decay: 0.0
adam_beta1: 0.9
adam_beta2: 0.999
adam_epsilon: 1e-08
max_grad_norm: 1.0
num_train_epochs: 30.0
max_steps: -1
lr_scheduler_type: linear
warmup_ratio: 0.0
warmup_steps: 0
logging_dir: 'output/meta_2023-06-10-11-54-24516_uie-base-en_spotasoc_absa_14lap_e30_linear_lr1e-4_ls0_b16_wu0_n-1_run1_log'
logging_strategy: steps
logging_first_step: False
logging_steps: 500
save_strategy: 'epoch'
save_steps: 500
save_total_limit: 1
no_cuda: False
seed: 4210
fp16: True
fp16_backend: 'auto'
fp16_full_eval: False
local_rank: -1
tpu_num_cores: None
tpu_metrics_debug: False
debug: []
dataloader_drop_last: False
eval_steps: 0
dataloader_num_workers: 0
past_index: -1
run_name: 'output/meta_2023-06-10-10-35-17161_uie-base-en_spotasoc_absa_14lap_e30_linear_lr1e-4_ls0_b16_wu0_n-1_run1'
disable_tqdm: True
remove_unused_columns: False
label_names: None
load_best_model_at_end: True
metric_for_best_model: 'eval_overall-F1'
greater_is_better: True
ignore_data_skip: False
sharded_ddp: []
label_smoothing_factor: 0.0
adafactor: False
group_by_length: False
length_column_name: 'length'
report_to: []
ddp_find_unused_parameters: False
dataloader_pin_memory: True
skip_memory_metrics: True
use_legacy_prediction_loop: False
push_to_hub: False
resume_from_checkpoint: None
mp_parameters: ''
sortish_sampler: False
predict_with_generate: True
constraint_decoding: False
save_better_checkpoint: False
start_eval_step: 0
